# -*- coding: utf-8 -*-
"""Metode Trapezoid.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AqJywnP6KRDYIgK6YsdDfb__ang01r2S

Firman Gani Heriansyah - 21120122130043 - Kelas C

Metode Trapezoid
"""

import numpy as np
import time

# Fungsi untuk dihitung integralnya
def f(x):
    return 4 / (1 + x**2)

# Metode trapezoid
def trapezoid_integral(a, b, N):
    h = (b - a) / N
    x = np.linspace(a, b, N + 1)
    y = f(x)
    integral = (h / 2) * (y[0] + 2 * np.sum(y[1:N]) + y[N])
    return integral

# Menghitung galat RMS
def calculate_rms_error(estimated_pi, true_pi):
    return np.sqrt((estimated_pi - true_pi)**2)

# Pengujian dengan variasi N
def run_tests():
    a = 0
    b = 1
    true_pi = 3.14159265358979323846
    N_values = [10, 100, 1000, 10000]
    results = []

    for N in N_values:
        start_time = time.time()
        estimated_pi = trapezoid_integral(a, b, N)
        execution_time = time.time() - start_time
        rms_error = calculate_rms_error(estimated_pi, true_pi)
        results.append((N, estimated_pi, rms_error, execution_time))

    return results

# Pengujian
results = run_tests()

# Cetak hasil pengujian
for N, estimated_pi, rms_error, execution_time in results:
    print(f"N: {N}, Estimated Pi: {estimated_pi}, RMS Error: {rms_error}, Execution Time: {execution_time} seconds")